# Generated by Django 4.2.17 on 2024-12-17 17:14

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.validate_due_date]),
        ),
    ]
